"""Added Cheque Fields

Revision ID: 92d7b557f856
Revises: 2d216c34a8d6
Create Date: 2026-05-06 15:04:32.646290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92d7b557f856'
down_revision = '2d216c34a8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cheque_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cheque_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.drop_column('cheque_date')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('cheque_no')



    # ### end Alembic commands ###
